### ISSUE TITLE
Remez code

### ISSUE THREAD

**Issue by roger-** [abiy-tasissa/abiy-tasissa.github.io#1]
I noticed in your [remez report](https://sites.tufts.edu/atasissa/files/2019/09/remez.pdf) you mentioned Python code for the rational case. Is this code available somewhere?

Thanks!

**Comment by abiy-tasissa** [comment]
Sorry for the late reply, I have now attached the code to this email.

Code was written a long time ago when I was a student, so is not optimized
or best written, feel free to modify/adapt as you see fit.

Regards,
Abiy

**Comment by roger-** [comment]
Thanks much, unfortunately  I’m not seeing the attachment though?

**Comment by abiy-tasissa** [comment]
No problem, it looks like Github is not showing my attachment, could you
send me an email directly to ***@***.*** and I can re-attach there

**Comment by roger-** [comment]
GitHub isn’t making this easy, looks like it censored your address. Are you open to posting it on this repo (you can just drag and drop it) or on a gist?

**Comment by abiy-tasissa** [comment]
Yes, I have just posted it on the repo

**Comment by roger-** [comment]
Much appreciated, thanks!
